[admiral]
items = ["left", "workspaces",
         "center", "title",
         "right", "clock"]

[workspaces]
path = "./bspwm_workspaces.sh"

[title]
path = "xtitle -s -t 100"

[clock]
path = "date '+%-I:%M%p  '"
reload = 1

# Used for formatting lemonbar
[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true
